name: Deploy to Production

on:
  push:
    branches:
      - production
  workflow_dispatch: # Allows manual triggering

env:
  # Base path for MU plugins
  MU_PLUGINS_BASE_PATH: '/public/wp-content/mu-plugins'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better git operations

      - name: Set plugin paths
        id: plugin-path
        run: |
          # MU plugin name from repo
          PLUGIN_NAME="${{ github.event.repository.name }}"

          # For MU plugins, deploy to the subfolder path
          REMOTE_PATH="${{ env.MU_PLUGINS_BASE_PATH }}/${PLUGIN_NAME}/"

          echo "remote_path=${REMOTE_PATH}" >> $GITHUB_OUTPUT
          echo "plugin_name=${PLUGIN_NAME}" >> $GITHUB_OUTPUT
          echo "📁 Deploying MU plugin subdirectory to: ${REMOTE_PATH}"

      - name: Deploy plugin subdirectory to Production via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SIERRA_SFTP_HOST }}
          username: ${{ secrets.SIERRA_PRODUCTION_SFTP_USERNAME }}
          password: ${{ secrets.SIERRA_PRODUCTION_SFTP_PASSWORD }}
          port: ${{ secrets.SIERRA_SFTP_PORT }}
          protocol: ftps
          # Deploy plugin subdirectory
          server-dir: ${{ steps.plugin-path.outputs.remote_path }}

          # Exclude development files
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/.env*
            .github/**
            .vscode/**

          log-level: verbose

      - name: Deploy loader file to mu-plugins root
        run: |
          # The loader file (unified-docs.php) needs to be in the parent mu-plugins directory
          # We'll use curl to upload it via FTPS
          LOADER_FILE="../${{ steps.plugin-path.outputs.plugin_name }}.php"

          if [ -f "$LOADER_FILE" ]; then
            echo "📄 Deploying loader file: ${{ steps.plugin-path.outputs.plugin_name }}.php"

            curl -T "$LOADER_FILE" \
              --ssl-reqd \
              --ftp-ssl \
              --user "${{ secrets.SIERRA_PRODUCTION_SFTP_USERNAME }}:${{ secrets.SIERRA_PRODUCTION_SFTP_PASSWORD }}" \
              "ftps://${{ secrets.SIERRA_SFTP_HOST }}:${{ secrets.SIERRA_SFTP_PORT }}${{ env.MU_PLUGINS_BASE_PATH }}/${{ steps.plugin-path.outputs.plugin_name }}.php"

            echo "✅ Loader file deployed"
          else
            echo "⚠️  Loader file not found at $LOADER_FILE"
            echo "This MU plugin may not work without it!"
            exit 1
          fi

      - name: Deployment Summary
        if: success()
        run: |
          echo "✅ Successfully deployed ${{ steps.plugin-path.outputs.plugin_name }} MU plugin to production!"
          echo "📁 Plugin directory: ${{ steps.plugin-path.outputs.remote_path }}"
          echo "📄 Loader file: ${{ env.MU_PLUGINS_BASE_PATH }}/${{ steps.plugin-path.outputs.plugin_name }}.php"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "🔨 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Deployment failed for ${{ steps.plugin-path.outputs.plugin_name }}!"
          echo "Please check the logs above for details."
